### ISSUE TITLE
Upgrade path to 2.1 is broken

### ISSUE THREAD

**Issue by devrimgunduz** [munakoiso/logerrors#18]
Hi,

Matej Klonfar reported that upgrade path to 2.1 is broken:  https://redmine.postgresql.org/issues/7770#note-4

This is caused by a missing file in Makefile. Attached is a patch for that.

[logerrors-2.1-makefile.patch.txt](https://github.com/munakoiso/logerrors/files/10677198/logerrors-2.1-makefile.patch.txt)

Can you please review it? I already added to RPM packages, to fix it ASAP.

Thanks!

Regards, Devrim

**Comment by munakoiso** [comment]
Hi,

Thank you for the report, patch was merged here
https://github.com/munakoiso/logerrors/pull/19
