### ISSUE TITLE
PostgreSQL 17 support

### ISSUE THREAD

**Issue by devrimgunduz** [munakoiso/logerrors#27]
Hi,

PostgreSQL 17 Beta1 is out and logerrors cannot be built against it. Below are the errors. Can you please take a look? Thanks! Devrim

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include  -c -o logerrors.o logerrors.c
> /usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -Wno-format-truncation -O2  -I. -I./ -I/usr/pgsql-17/include/server -I/usr/pgsql-17/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2 -DWITH_GZFILEOP  -I/usr/include -flto=thin -emit-llvm -c -o logerrors.bc logerrors.c
> logerrors.c:686:5: error: call to undeclared function 'tuplestore_donestoring'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>   686 |     tuplestore_donestoring(tupstore);
>       |     ^
> logerrors.c:761:5: error: call to undeclared function 'tuplestore_donestoring'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>   761 |     tuplestore_donestoring(tupstore);
>       |     ^
> 2 errors generated.
> make[1]: *** [/usr/pgsql-17/lib/pgxs/src/makefiles/../../src/Makefile.global:1085: logerrors.bc] Error 1
> make[1]: *** Waiting for unfinished jobs....
> logerrors.c: In function ‘pg_log_errors_stats’:
> logerrors.c:686:5: error: implicit declaration of function ‘tuplestore_donestoring’; did you mean ‘tuplestore_rescan’? [-Wimplicit-function-declaration]
>   686 |     tuplestore_donestoring(tupstore);
>       |     ^~~~~~~~~~~~~~~~~~~~~~
>       |     tuplestore_rescan
> make[1]: *** [<builtin>: logerrors.o] Error 1
>

**Comment by munakoiso** [comment]
Hi,

Sure, I'll take a look.

**Comment by devrimgunduz** [comment]
I can confirm that this patch fixes the problem. Thanks!

**Comment by devrimgunduz** [comment]
Any updates?

**Comment by munakoiso** [comment]
Unfortunately, I still haven't found time to look :( 
I'm pretty sure my colleagues will fix the bug before the major release.

**Comment by devrimgunduz** [comment]
Hi,

Attached patch fixes the problem:

[logerrors-pg17-fix.patch.txt](https://github.com/user-attachments/files/16428320/logerrors-pg17-fix.patch.txt)

**Comment by reshke** [comment]
> Hi,
> 
> Attached patch fixes the problem:
> 
> [logerrors-pg17-fix.patch.txt](https://github.com/user-attachments/files/16428320/logerrors-pg17-fix.patch.txt)

Hi! Thanks for taking care.
https://github.com/munakoiso/logerrors/pull/28 merged, should be OK now

**Comment by devrimgunduz** [comment]
Hi,

It works fine. Can you please push a new release so that I can build the RPMs?

Regards, Devrim

**Comment by munakoiso** [comment]
Hi

I'm sorry for the delay. 
I have just released a new version: https://github.com/munakoiso/logerrors/releases/tag/v2.1.3

**Comment by devrimgunduz** [comment]
Thanks!
