### ISSUE TITLE
Unsafe actions in log emission hook

### ISSUE THREAD

**Issue by anarazel** [munakoiso/logerrors#6]
Hi,

Nice extension. I just briefly looked at it because I saw it via in https://twitter.com/samokhvalov/status/1326328587960549376

I noticed that you perform a few unsafe operations in the log emission hook, see
https://github.com/munakoiso/logerrors/blob/097e78f91ccfbaf26a8e9c4d7835343eb0e57aaa/logerrors.c#L281

You cannot safely perform catalog or buffer accesses from within the log hook - it might e.g. called with an lwlock for a pg_database already held, causing an undetected deadlock. You might also get wrong results, because you're in a semi-aborted transaction at this point. Even acquiring just your extension's lwlock is possibly dangerous, if there ever is a chance you could throw an error or accept interrupts while holding it.

The database oid can be acquired much more simply, by just using `MyDatabaseId`. Similarly, `GetSessionUserId()`, `GetUserId()` or `GetAuthenticatedUserId()` should also be unproblematic.

Regards,

Andres

**Comment by munakoiso** [comment]
Hi!

Thanks for your comment, i will fix it in the near future.

**Comment by munakoiso** [comment]
Fixed here
https://github.com/munakoiso/logerrors/pull/7
